[package]
name = "differential-reasoner"
version = "0.2.0"
edition = "2018"

[dependencies]
timely = "0.12.0"
differential-dataflow = "0.12.0"
criterion = "0.3.4"
lasso = "0.5.0"
clap = "3.0.0-beta.4"
linecount = "0.1.0"