[package]
name = "rdfs-materialization"
version = "0.2.0"
authors = ["bruno_rucy <brurucy@gmail.com>"]
edition = "2018"

[dependencies]
timely = "0.12.0"
differential-dataflow = "0.12.0"
criterion = "0.3.4"
lasso = "0.5.1"

[[bench]]
name = "bench_main"
harness = false